[tool.poetry]
name = "blya_bot"
version = "0.1.0"
description = ""
authors = ["Alexey Zakharov <dokzlo13@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^2.21"
python-dotenv = "^0.20.0"
pydub = "^0.25.1"
vosk = "^0.3.43"
emoji = "^2.0.0"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-isort = "^4.1.1"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.7.1"
flake8-black = "^0.3.3"
bandit = "^1.7.4"
black = "^22.6.0"
mypy = "^0.971"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
