name: blya-bot-app
region: ams
services:
- dockerfile_path: Dockerfile-vosk
  envs:
  - key: HEALTH_CHECK_PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  - key: HEALTH_CHECK_HOST
    scope: RUN_AND_BUILD_TIME
    value: 0.0.0.0
  github:
    branch: master
    deploy_on_push: true
