# syntax = docker/dockerfile:1.0-experimental

FROM python:3.10.8-slim-buster

ARG ENVIRONMENT
ENV ENVIRONMENT=${ENVIRONMENT:-production}
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /app/models
WORKDIR /app

RUN pip install --upgrade pip && pip install -U pip poetry==1.2.2
RUN poetry config virtualenvs.create false

RUN apt-get update && apt-get install --no-install-recommends --yes \
    wget \
    zip \
    unzip \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Forcing certificates
RUN wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt && update-ca-certificates

# TODO: Get downloand link dynamically?
RUN wget -O /app/models/vosk-model-ru-0.22.zip https://alphacephei.com/vosk/models/vosk-model-ru-0.22.zip \
    && unzip '/app/models/vosk-model-ru-0.22.zip' -d /app/models/ && rm /app/models/vosk-model-ru-0.22.zip || true;

COPY poetry.lock /app
COPY pyproject.toml /app

RUN poetry install --no-dev --no-root -E "vosk" -E "pymorphy"\
    && if [ "$ENVIRONMENT" = "development" ]; then poetry install --all-extras; fi

ENV RECOGNITION_ENGINE="vosk"
ENV RECOGNITION_ENGINE_OPTIONS='{"model_path": "/app/models/vosk-model-ru-0.22"}'

ADD fixtures /app/fixtures
ADD blya_bot /app/blya_bot

ENV PATH="/app:${PATH}"
CMD ["python", "-m", "blya_bot"]
